### ISSUE TITLE
Not able to rdp from mac

### ISSUE THREAD

**Issue by fa185084** [kaivalya97/rdp-iap-mac#1]
Getting below Error:
The file /Users/AB112/Documents/test/testing/rdp:/full%20address=s:localhost:&username:s:ab112&audiomode=i:0&disable%20themes=i:1&desktopwidth:i:&desktopheight:i:&prompt%20for%20credentials%20on%20client:i:0 does not exist.
rm: tmp: No such file or directory

Using Microsoft Remote Desktop: https://go.microsoft.com/fwlink/?linkid=868963

**Comment by corbinweigel** [comment]
@fa185084 @kaivalya97 

This is related to how the URI is interpreted with the open command in Big Sur. I was able to resolve this issue by editing line 19 and removing the "//" after rdp:. 

Example: open -n -F -a /Applications/Microsoft\ Remote\ Desktop.app "rdp:full%20address=s:localhost:$port&username:s:$username&audiomode=i:0&disable%20themes=i:1&desktopwidth:i:$width&desktopheight:i:$height&prompt%20for%20credentials%20on%20client:i:0"

I am on Big Sur 11.5.2. Not sure if this would work on Catalina or not, so this may be better off as an anecdote in the readme instead of a full pull request.

**Comment by fa185084** [comment]
That worked for me. Thank you @corbinweigel
